Send Check First & Separate Out Errors
custom-components/healthchecksio pull request #43
Opened 2023-08-08 02:11 UTC by Snuffy2

* Send the Check first before getting the data from HealthCheck. That way, the Check should be reflected in the Data downloaded.
* Separate out the error checks to be more discrete. Should give more specific errors and allow the integration to fail more gracefully so it will continue to update every 5 min even if there is an error

Fixes #38

2023-10-09 10:26 UTC, ludeeus requested changes

2023-10-09 10:26 UTC, ludeeus commented on custom_components/healthchecksio/config_flow.py
> +                return False
```suggestion
            if not data.ok:
                Logger("custom_components.healthchecksio").error(
                    f"Error: Get Data HTTP Status Code: {data.status}"
                )
                return False
            Logger("custom_components.healthchecksio").debug(
                f"Get Data HTTP Status Code: {data.status}"
            )
            return True
```

2023-10-09 10:26 UTC, ludeeus commented on custom_components/healthchecksio/__init__.py
> +            ) as data:
```suggestion
            data = await session.get(
                f"{self.site_root}/api/v1/checks/",
                headers=headers,
                timeout=timeout10,
            )
```

2023-10-09 10:26 UTC, ludeeus commented on custom_components/healthchecksio/config_flow.py
> +            ) as data:
```suggestion
            data = await session.get(
                f"{site_root}/api/v1/checks/",
                headers=headers,
                timeout=timeout10,
            )
```

2023-10-09 10:26 UTC, ludeeus commented on custom_components/healthchecksio/config_flow.py
>                  self.hass.data[DOMAIN_DATA] = {"data": await data.json()}
```suggestion
            self.hass.data[DOMAIN_DATA] = {"data": await data.json()}
```

2023-10-09 10:26 UTC, ludeeus commented on custom_components/healthchecksio/__init__.py
>                  self.hass.data[DOMAIN_DATA]["data"] = await data.json()
```suggestion
            self.hass.data[DOMAIN_DATA]["data"] = await data.json()
```

2023-10-09 23:11 UTC, Snuffy2 reviewed
All requested changes implemented.

2024-06-30 00:55 UTC, Snuffy2 commented
@ludeeus, any chance of getting this and #46 reviewed/merged?

2024-07-23 07:31 UTC, ludeeus approved these changes

2024-07-23 07:31 UTC, merged